easy_page:
  page_class: App\Entity\EasyPage\Page
  page_repository: App\Repository\EasyPage\PageRepository
  page_controller: App\Controller\EasyPage\PageController

  layouts:
    front:
      resource: '@EasyPage/default_layout.html.twig'
      pattern: ''
      assets_css:
        - 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css'
      assets_js:
        - 'https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js'


services:
    App\Controller\Page\PageController:
        calls:
            - [ 'setRepository', [ '@easy_page.repository' ] ]
