easy_admin_user:
  user_class: App\Entity\EasyAdmin\User
  user_repository: App\Repository\EasyAdmin\UserRepository
  reset_password_class: App\Entity\EasyAdmin\ResetPasswordRequest
  reset_password_repository: App\Repository\EasyAdmin\ResetPasswordRequestRepository

symfonycasts_reset_password:
  request_password_repository: easy_admin_user.reset_password_repository
