easy_page:
  page_class: App\Entity\EasyPage\Page
  page_repository: App\Repository\EasyPage\PageRepository
  page_controller: App\Controller\EasyPage\PageController


services:
    App\Controller\Page\PageController:
        calls:
            - [ 'setRepository', [ '@easy_page.repository' ] ]
