name: Update Flex endpoint

on:
  workflow_call:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  call-flex-update:
    uses: symfony/recipes/.github/workflows/callable-flex-update.yml@main
    with:
      contrib: true
